name: Fetch Spotify

on:
  schedule:
    - cron: "*/15 * * * *"   # every ~15 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          python spotify_stats_extended.py

      - name: Commit CSV updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add spotify_stats.csv spotify_top_tracks.csv runs.log || true
          git commit -m "Spotify: update stats [skip ci]" || echo "No changes to commit"
          git push
